### ISSUE TITLE
Feature request: "best" stories

### ISSUE THREAD

**Issue by apepper** [bonzoq/hniosreader#3]
First of all thank you for this wonderful hacker news client. I use it daily and enjoy it's elegance.

It would be great to have support for "best" stories, which can be accessed via https://news.ycombinator.com/best . Those stories have the highest points in the last 3 days. So it's a good place to find high quality stories.

**Comment by apepper** [comment]
Any updates?

**Comment by bonzoq** [comment]
Sadly I decided not to use any Hacker News APIs but the official one. Once it is extended with the "best" stories, I'll add them.

**Comment by apepper** [comment]
@bonzoq Where can I find the official Hacker News APIs, so I can lobby for adding "best" stories?

**Comment by bonzoq** [comment]
You can find it here: https://github.com/HackerNews/API .

**Comment by apepper** [comment]
@bonzoq Thank you.

**Comment by bonzoq** [comment]
@apepper You're welcome.

**Comment by apepper** [comment]
Wow, the Hacker News API team is super fast:

> Turns out it was trivial to add, so we've done so. You should now be able to access the /best ids at https://hacker-news.firebaseio.com/v0/beststories.json.  Let us know if you have any trouble.

@bonzoq Can you try it out?

**Comment by bonzoq** [comment]
Wow, that was really fast. 

I won't take longer though.

I already pushed a commit with best stories added to the app to github. I'm going to submit it to AppStore now. The average AppStore review time is around 5 days now. 

Thanks!

**Comment by apepper** [comment]
Awesome! Thank you.
