### ISSUE TITLE
Slow start

### ISSUE THREAD

**Issue by lrusnac** [bonzoq/hniosreader#8]
Hi, I don't know if is the app or my old iPhone 4s, but the application is slow in the beginning:
I open the app, I view the first stories, but I can't open or scroll for 45-60 seconds, it seems frozen, then all works well.

**Comment by bonzoq** [comment]
Hi, have you updated the app to v.2.0?

**Comment by lrusnac** [comment]
Yes

**Comment by bonzoq** [comment]
Ok I will take a look at it using the xcode simulator.

**Comment by lrusnac** [comment]
any news? it's frustrating :)

**Comment by bonzoq** [comment]
Hi, I will be rolling out an update in the upcoming weeks.

**Comment by lrusnac** [comment]
it is still really slow, I need to change the app, sorry
